// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkFqBxe3byrLLz5aANau6bw2EzY95o8vY',
    appId: '1:793627216817:web:f7689b90708727ef91cb90',
    messagingSenderId: '793627216817',
    projectId: 'app-vehiculos-b4259',
    authDomain: 'app-vehiculos-b4259.firebaseapp.com',
    storageBucket: 'app-vehiculos-b4259.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBp32ix3tUU6UCnxXpa6sb7jopaJ99LL1Y',
    appId: '1:793627216817:android:742aca7adb150b1191cb90',
    messagingSenderId: '793627216817',
    projectId: 'app-vehiculos-b4259',
    storageBucket: 'app-vehiculos-b4259.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWDgRQ5k5NGyBGcpLqoGW7ArnlLhLOrt4',
    appId: '1:793627216817:ios:cc4fa48ca5ff358a91cb90',
    messagingSenderId: '793627216817',
    projectId: 'app-vehiculos-b4259',
    storageBucket: 'app-vehiculos-b4259.firebasestorage.app',
    iosBundleId: 'com.example.appVehiculos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWDgRQ5k5NGyBGcpLqoGW7ArnlLhLOrt4',
    appId: '1:793627216817:ios:cc4fa48ca5ff358a91cb90',
    messagingSenderId: '793627216817',
    projectId: 'app-vehiculos-b4259',
    storageBucket: 'app-vehiculos-b4259.firebasestorage.app',
    iosBundleId: 'com.example.appVehiculos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkFqBxe3byrLLz5aANau6bw2EzY95o8vY',
    appId: '1:793627216817:web:4819168553d4eefe91cb90',
    messagingSenderId: '793627216817',
    projectId: 'app-vehiculos-b4259',
    authDomain: 'app-vehiculos-b4259.firebaseapp.com',
    storageBucket: 'app-vehiculos-b4259.firebasestorage.app',
  );
}
